In [89]:
import sqlite3
import pandas as pd
import numpy as np

In [90]:
df = pd.read_csv(r'C:\Users\LENOVO\Project-2-\imdb_top_1000.csv')

## Import Dataset in SQL :

In [91]:
conn = sqlite3.connect('imdb_universe.db')

df.to_sql('movies', conn, if_exists='replace', index=False)

1000

In [92]:
query = 'SELECT * FROM movies;'
df = pd.read_sql(query, conn)

## Understanding data :

In [93]:
df.head()

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
0,https://m.media-amazon.com/images/M/MV5BMDFkYT...,The Shawshank Redemption,1994,A,142 min,Drama,9.3,Two imprisoned men bond over a number of years...,80.0,Frank Darabont,Tim Robbins,Morgan Freeman,Bob Gunton,William Sadler,2343110,"28,341,469"
1,https://m.media-amazon.com/images/M/MV5BM2MyNj...,The Godfather,1972,A,175 min,"Crime, Drama",9.2,An organized crime dynasty's aging patriarch t...,100.0,Francis Ford Coppola,Marlon Brando,Al Pacino,James Caan,Diane Keaton,1620367,"134,966,411"
2,https://m.media-amazon.com/images/M/MV5BMTMxNT...,The Dark Knight,2008,UA,152 min,"Action, Crime, Drama",9.0,When the menace known as the Joker wreaks havo...,84.0,Christopher Nolan,Christian Bale,Heath Ledger,Aaron Eckhart,Michael Caine,2303232,"534,858,444"
3,https://m.media-amazon.com/images/M/MV5BMWMwMG...,The Godfather: Part II,1974,A,202 min,"Crime, Drama",9.0,The early life and career of Vito Corleone in ...,90.0,Francis Ford Coppola,Al Pacino,Robert De Niro,Robert Duvall,Diane Keaton,1129952,"57,300,000"
4,https://m.media-amazon.com/images/M/MV5BMWU4N2...,12 Angry Men,1957,U,96 min,"Crime, Drama",9.0,A jury holdout attempts to prevent a miscarria...,96.0,Sidney Lumet,Henry Fonda,Lee J. Cobb,Martin Balsam,John Fiedler,689845,"4,360,000"

In [94]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 16 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Poster_Link    1000 non-null   str
 1   Series_Title   1000 non-null   str
 2   Released_Year  1000 non-null   str
 3   Certificate    899 non-null    str
 4   Runtime        1000 non-null   str
 5   Genre          1000 non-null   str
 6   IMDB_Rating    1000 non-null   float64
 7   Overview       1000 non-null   str
 8   Meta_score     843 non-null    float64
 9   Director       1000 non-null   str
 10  Star1          1000 non-null   str
 11  Star2          1000 non-null   str
 12  Star3          1000 non-null   str
 13  Star4          1000 non-null   str
 14  No_of_Votes    1000 non-null   int64
 15  Gross          831 non-null    str
dtypes: float64(2), int64(1), str(13)
memory usage: 520.0 KB

In [95]:
df.describe()

       IMDB_Rating  Meta_score   No_of_Votes
count  1000.000000  843.000000  1.000000e+03
mean      7.949300   77.971530  2.736929e+05
std       0.275491   12.376099  3.273727e+05
min       7.600000   28.000000  2.508800e+04
25%       7.700000   70.000000  5.552625e+04
50%       7.900000   79.000000  1.385485e+05
75%       8.100000   87.000000  3.741612e+05
max       9.300000  100.000000  2.343110e+06

## 1. Data Cleaning :

### A. Removing The Useless Columns :

In [96]:
df.head(0)

Empty DataFrame
Columns: [Poster_Link, Series_Title, Released_Year, Certificate, Runtime, Genre, IMDB_Rating, Overview, Meta_score, Director, Star1, Star2, Star3, Star4, No_of_Votes, Gross]
Index: []

In [97]:
df = df.drop(columns=['Poster_Link', 'Overview'])

In [102]:
df.head(4)

,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
0,The Shawshank Redemption,1994,A,142 min,Drama,9.3,80.0,Frank Darabont,Tim Robbins,Morgan Freeman,Bob Gunton,William Sadler,2343110,"28,341,469"
1,The Godfather,1972,A,175 min,"Crime, Drama",9.2,100.0,Francis Ford Coppola,Marlon Brando,Al Pacino,James Caan,Diane Keaton,1620367,"134,966,411"
2,The Dark Knight,2008,UA,152 min,"Action, Crime, Drama",9.0,84.0,Christopher Nolan,Christian Bale,Heath Ledger,Aaron Eckhart,Michael Caine,2303232,"534,858,444"
3,The Godfather: Part II,1974,A,202 min,"Crime, Drama",9.0,90.0,Francis Ford Coppola,Al Pacino,Robert De Niro,Robert Duvall,Diane Keaton,1129952,"57,300,000"

### B. Replace NULL values with Passed in Certificate column :

In [99]:
# In this dataset there are muliple certificates of movies are not available.
# so i m assuming that these movies are passed.


df['Certificate'] = df['Certificate'].replace(np.nan, 'Passed')

### C. Replacing the NULL values in Meta score :

In [101]:
df['Meta_score'].isnull().sum()

np.int64(0)

In [ ]:
# there are around 157 values are null in this column 
# this data is important for me thats why i m using ffill for replacing null values. 


df['Meta_score']= df['Meta_score'].ffill()

### D. Handling The NULL values in Gross column :

In [105]:
df['Gross'].isnull().sum()

np.int64(169)

In [109]:
df[df['Gross'].isnull()].head(20)

,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
18,Hamilton,2020,PG-13,160 min,"Biography, Drama, History",8.6,90.0,Thomas Kail,Lin-Manuel Miranda,Phillipa Soo,Leslie Odom Jr.,Renée Elise Goldsberry,55291,NaN
20,Soorarai Pottru,2020,U,153 min,Drama,8.6,96.0,Sudha Kongara,Suriya,Madhavan,Paresh Rawal,Aparna Balamurali,54995,NaN
30,Seppuku,1962,Passed,133 min,"Action, Drama, Mystery",8.6,85.0,Masaki Kobayashi,Tatsuya Nakadai,Akira Ishihama,Shima Iwashita,Tetsurô Tanba,42004,NaN
32,It's a Wonderful Life,1946,PG,130 min,"Drama, Family, Fantasy",8.6,89.0,Frank Capra,James Stewart,Donna Reed,Lionel Barrymore,Thomas Mitchell,405801,NaN
46,Hotaru no haka,1988,U,89 min,"Animation, Drama, War",8.5,94.0,Isao Takahata,Tsutomu Tatsumi,Ayano Shiraishi,Akemi Yamaguchi,Yoshiko Shinohara,235231,NaN
54,Ayla: The Daughter of War,2017,Passed,125 min,"Biography, Drama, History",8.4,75.0,Can Ulkay,Erdem Can,Çetin Tekindor,Ismail Hacioglu,Kyung-jin Lee,34112,NaN
55,Vikram Vedha,2017,UA,147 min,"Action, Crime, Drama",8.4,75.0,Gayatri,Pushkar,Madhavan,Vijay Sethupathi,Shraddha Srinath,28401,NaN
76,Anand,1971,U,122 min,"Drama, Musical",8.4,89.0,Hrishikesh Mukherjee,Rajesh Khanna,Amitabh Bachchan,Sumita Sanyal,Ramesh Deo,30273,NaN
77,Tengoku to jigoku,1963,Passed,143 min,"Crime, Drama, Mystery",8.4,89.0,Akira Kurosawa,Toshirô Mifune,Yutaka Sada,Tatsuya Nakadai,Kyôko Kagawa,34357,NaN
80,Paths of Glory,1957,A,88 min,"Drama, War",8.4,90.0,Stanley Kubrick,Kirk Douglas,Ralph Meeker,Adolphe Menjou,George Macready,178092,NaN
82,Sunset Blvd.,1950,Passed,110 min,"Drama, Film-Noir",8.4,100.0,Billy Wilder,William Holden,Gloria Swanson,Erich von Stroheim,Nancy Olson,201632,NaN
85,Tumbbad,2018,A,104 min,"Drama, Fantasy, Horror",8.3,78.0,Rahi Anil Barve,Anand Gandhi,Adesh Prasad,Sohum Shah,Jyoti Malshe,27793,NaN
87,Drishyam,2013,U,160 min,"Crime, Drama, Thriller",8.3,78.0,Jeethu Joseph,Mohanlal,Meena,Asha Sharath,Ansiba,30722,NaN
91,Miracle in cell NO.7,2019,TV-14,132 min,Drama,8.3,80.0,Mehmet Ada Öztekin,Aras Bulut Iynemli,Nisa Sofiya Aksongur,Deniz Baysal,Celile Toyon Uysal,33935,NaN
92,Babam ve Oglum,2005,Passed,112 min,"Drama, Family",8.3,80.0,Çagan Irmak,Çetin Tekindor,Fikret Kuskan,Hümeyra,Ege Tanman,78925,NaN
105,Idi i smotri,1985,A,142 min,"Drama, Thriller, War",8.3,76.0,Elem Klimov,Aleksey Kravchenko,Olga Mironova,Liubomiras Laucevicius,Vladas Bagdonas,59056,NaN
130,K.G.F: Chapter 1,2018,UA,156 min,"Action, Drama",8.2,98.0,Prashanth Neel,Yash,Srinidhi Shetty,Ramachandra Raju,Archana Jois,36680,NaN
135,Klaus,2019,PG,96 min,"Animation, Adventure, Comedy",8.2,65.0,Sergio Pablos,Carlos Martínez López,Jason Schwartzman,J.K. Simmons,Rashida Jones,104761,NaN
140,Gangs of Wasseypur,2012,A,321 min,"Action, Comedy, Crime",8.2,89.0,Anurag Kashyap,Manoj Bajpayee,Richa Chadha,Nawazuddin Siddiqui,Tigmanshu Dhulia,82365,NaN
160,Hera Pheri,2000,U,156 min,"Action, Comedy, Crime",8.2,72.0,Priyadarshan,Akshay Kumar,Sunil Shetty,Paresh Rawal,Tabu,57057,NaN